import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href='/pra-1'>
        <a>
          Practica 1 
        </a>
      </Link>
      <Link href='/pra-2'>
        <a>
          Practica 2
        </a>
      </Link>
    </div>
  )
}
